steps:
# This step runs the unit tests on the app
- name: 'docker.io/library/python:3.7'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install -U pytest && pip install apache-beam[gcp] && pytest'
- name: 'docker.io/library/python:3.7'
  id: dataflow_bq_test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install apache-beam[gcp] && python -m test_bq_io_ut --region central1 --runner DirectRunner --project acn-montreal-ai-hackathon --num_records 418 --input_table bqml_tutorial.titanic_dataset_test --temp_location gs://dataflow-staging-northamerica-northeast1-426605919781/temp/ --staging_location gs://dataflow-staging-northamerica-northeast1-426605919781/temp/ --noauth_local_webserver --service_account_email data-studio@acn-montreal-ai-hackathon.iam.gserviceaccount.com'
